version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: drools-postgres
    environment:
      POSTGRES_USER: hoss
      POSTGRES_PASSWORD: 123456P
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
