version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    environment:
      POSTGRES_USER: hoss
      POSTGRES_PASSWORD: 123456P
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: