version: '3.8'

services:
  mongodb:
    image: mongo:8.0.10
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: hoss
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: contract
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 3

volumes:
  mongodb_data: